### PR TITLE
Avoid compilation error -- can't use always_inline with USE_LLVM_BITCODE=0

### PR DESCRIPTION
**Pull request by lgritz**
This was broken by #1114. 

In a second PR coming later, I will add a testsuite entry where we build with `USE_LLVM_BITCODE=0` just so that this code path cannot be easily broken again.

### CODE REVIEW

**Comment by AlexMWells** [comment]
Like the noinline addition.

LGTM
