### ISSUE TITLE
LLVM-3.7 MCJIT

### ISSUE THREAD

**Issue by ReubenM** [imageworks/OpenShadingLanguage#631]
In theory if 3.6 is supported, 3.7 should work also since the ORCJIT does no come at the expense of the MCJIT, but is intended to complement it.

However, currnet HEAD is failing. (Specifically with LLVM-3.7.1)

```
./OpenShadingLanguage-Release/src/liboslexec/llvm_util.cpp: In member function ‘void OSL::pvt::LLVM_Util::SetupLLVM()’:
./OpenShadingLanguage-Release/src/liboslexec/llvm_util.cpp:347:49: error: ‘begin’ is not a member of ‘llvm::TargetRegistry’
         for (llvm::TargetRegistry::iterator t = llvm::TargetRegistry::begin();

./OpenShadingLanguage-Release/src/liboslexec/llvm_util.cpp:348:19: error: ‘end’ is not a member of ‘llvm::TargetRegistry’
              t != llvm::TargetRegistry::end();  ++t) {

./OpenShadingLanguage-Release/src/liboslexec/llvm_util.cpp: In member function ‘llvm::Module* OSL::pvt::LLVM_Util::module_from_bitcode(const char*, size_t, const string&, std::__cxx11::string*)’:
./OpenShadingLanguage-Release/src/liboslexec/llvm_util.cpp:392:72: error: conversion from ‘llvm::ErrorOr<std::unique_ptr<llvm::Module> >’ to non-scalar type ‘llvm::ErrorOr<llvm::Module*>’ requested
     llvm::ErrorOr<llvm::Module *> ModuleOrErr = llvm::parseBitcodeFile (buf, context());

./OpenShadingLanguage-Release/src/liboslexec/llvm_util.cpp: In member function ‘void OSL::pvt::LLVM_Util::setup_optimization_passes(int)’:
./OpenShadingLanguage-Release/src/liboslexec/llvm_util.cpp:524:18: error: expected type-specifier
     fpm.add (new llvm::DataLayoutPass());

./OpenShadingLanguage-Release/src/liboslexec/llvm_util.cpp:528:18: error: expected type-specifier

./OpenShadingLanguage-Release/src/liboslexec/llvm_util.cpp: In member function ‘void OSL::pvt::LLVM_Util::op_memset(llvm::Value*, int, llvm::Value*, int)’:
./OpenShadingLanguage-Release/src/liboslexec/llvm_util.cpp:1182:15: error: ‘OSL::pvt::LLVM_Util::IRBuilder {aka class llvm::IRBuilder<true, llvm::ConstantFolder, llvm::IRBuilderDefaultInserter<true> >}’ has no member named ‘CreateCall5’
     builder().CreateCall5 (func, ptr, fill_val, len, constant(align),

./OpenShadingLanguage-Release/src/liboslexec/llvm_util.cpp: In member function ‘void OSL::pvt::LLVM_Util::op_memcpy(llvm::Value*, llvm::Value*, int, int)’:
.OpenShadingLanguage-Release/src/liboslexec/llvm_util.cpp:1205:15: error: ‘OSL::pvt::LLVM_Util::IRBuilder {aka class llvm::IRBuilder<true, llvm::ConstantFolder, llvm::IRBuilderDefaultInserter<true> >}’ has no member named ‘CreateCall5’
     builder().CreateCall5 (func, dst, src,

./OpenShadingLanguage-Release/src/liboslexec/llvm_util.cpp: In member function ‘llvm::Value* OSL::pvt::LLVM_Util::GEP(llvm::Value*, int, int)’:
./OpenShadingLanguage-Release/src/liboslexec/llvm_util.cpp:1246:59: error: no matching function for call to ‘llvm::IRBuilder<true, llvm::ConstantFolder, llvm::IRBuilderDefaultInserter<true> >::CreateConstGEP2_32(llvm::Value*&, int&, int&)’
     return builder().CreateConstGEP2_32 (ptr, elem1, elem2);

In file included from ./OpenShadingLanguage-Release/src/liboslexec/llvm_util.cpp:54:0:
/usr/include/llvm/IR/IRBuilder.h:1104:10: note: candidate: llvm::Value* llvm::IRBuilder<preserveNames, T, Inserter>::CreateConstGEP2_32(llvm::Type*, llvm::Value*, unsigned int, unsigned int, const llvm::Twine&) [with bool preserveNames = true; T = llvm::ConstantFolder; Inserter = llvm::IRBuilderDefaultInserter<true>]
   Value *CreateConstGEP2_32(Type *Ty, Value *Ptr, unsigned Idx0, unsigned Idx1,

/usr/include/llvm/IR/IRBuilder.h:1104:10: note:   candidate expects 5 arguments, 3 provided
src/liboslexec/CMakeFiles/oslexec.dir/build.make:857: recipe for target 'src/liboslexec/CMakeFiles/oslexec.dir/llvm_util.cpp.o' failed
```
Everything else seems to build though...

**Comment by lgritz** [comment]
OSL is known not to work with LLVM > 3.5.

I'm working on this. Closing.

**Comment by ReubenM** [comment]
I was just assuming from your latest commits that you were able to get it to build with 3.6.

**Comment by lgritz** [comment]
Current status: It compiles against 3.6, and llvmutil_test (unit tests) works, but full-blown OSL compilation results in shaders that crash. But even if that was fixed, my implementation for llvm 3.6 has unacceptably bad memory bloat, because the trick I used with the old JIT to aggressively free LLVM memory (other than the resulting binary JIT code) doesn't work with 3.6 due to changed APIs and the way that MCJIT works, so I wouldn't consider it production-worthy solution.

I'm actually trying to push to LLVM 3.7 and beyond with ORC JIT, which as I understand it recaptures some of the memory reclamation that we desperately need. I'm working on this right now. If it works well, it may be that we skip LLVM 3.6 entirely and jump straight to only versions of ORC JIT (3.7+). But the production viability of this still is awaiting my finding out how the time and memory performance compare to the system we have built around LLVM 3.4/3.5.

**Comment by dracwyrm** [comment]
@lgritz Can't post this on your Github as you don't allow issues, so I hope you get this. I was trying your Orc Jit patches from here: https://github.com/lgritz/OpenShadingLanguage/tree/lg-orcjit
I applied them to the latest master code. I compiled with LLVM 3.8.1 and trying to use with Blender 2.78. I followed the script from here: http://elbrujodelatribu.blogspot.co.uk/2013/04/blender-cycles-osl-mandelbrot-fractal.html
To create my test script with something known to work.

However, Blender crashes with this:
src/liboslexec/llvm_instance.cpp:1097: failed assertion 'll.get_compiled_function(name)'
Aborted (core dumped)
That function was added with your code. I was wondering if you might be able to help me figure this out.

Again, sorry for posting here, but it's kinda relevant to this bug and the only way I can get a hold of @lgritz 

Cheers.

**Comment by lgritz** [comment]
The "lgritz" account is my private work area / boneyard, so of course it does not allow issues to file against it. You will find trees there in various states of disrepair, abandonment, and half-assedness. Never assume anything there works, it's not intended to ever be pulled by anybody.

The official OSL area is the imageworks/OpenShadingLanguage account. The currently supported LLVM versions are 3.4 and 3.5.
