### ISSUE TITLE
Still trying to simply build on ubuntu, RB-1.5

### ISSUE THREAD

**Issue by unicomp21** [imageworks/OpenShadingLanguage#452]
CMake Warning:
  Manually-specified variables were not used by the project:

```
SELF_CONTAINED_INSTALL_TREE
```

-- Build files have been written to: /root/OpenShadingLanguage/build/linux64
( cd build/linux64 ; make  )
make[1]: Entering directory '/root/OpenShadingLanguage/build/linux64'
make[2]: Entering directory '/root/OpenShadingLanguage/build/linux64'
make[3]: Entering directory '/root/OpenShadingLanguage/build/linux64'
[  1%] Generating osllex.cpp
[  2%] Generating oslgram.cpp
/root/OpenShadingLanguage/src/liboslcomp/oslgram.y: warning: 1 shift/reduce conf
lict [-Wconflicts-sr]
/root/OpenShadingLanguage/src/liboslcomp/oslgram.y: warning: 1 reduce/reduce con
flict [-Wconflicts-rr]
Scanning dependencies of target oslcomp
make[3]: Leaving directory '/root/OpenShadingLanguage/build/linux64'
make[3]: Entering directory '/root/OpenShadingLanguage/build/linux64'
[  3%] Building CXX object src/liboslcomp/CMakeFiles/oslcomp.dir/ast.cpp.o
In file included from /root/OpenShadingLanguage/src/liboslcomp/ast.cpp:35:
In file included from /root/OpenShadingLanguage/src/include/osl_pvt.h:31:
/root/OpenShadingLanguage/src/include/OSL/oslconfig.h:109:13: error: no member
      named 'string_view' in namespace 'OpenImageIO::v1_3'
using OIIO::string_view;
      ~~~~~~^
In file included from /root/OpenShadingLanguage/src/liboslcomp/ast.cpp:35:
/root/OpenShadingLanguage/src/include/osl_pvt.h:54:1: error: unknown type name
      'string_view'
string_view shadertypename (ShaderType s);
^
/root/OpenShadingLanguage/src/include/osl_pvt.h:58:34: error: unknown type name
      'string_view'
ShaderType shadertype_from_name (string_view name);
                                 ^
/root/OpenShadingLanguage/src/include/osl_pvt.h:76:32: error: unknown type name
      'string_view'
ShaderUse shaderuse_from_name (string_view name);
                               ^
In file included from /root/OpenShadingLanguage/src/liboslcomp/ast.cpp:36:
In file included from /root/OpenShadingLanguage/src/liboslcomp/oslcomp_pvt.h:36:

/root/OpenShadingLanguage/src/include/OSL/oslcomp.h:52:19: error: unknown type
      name 'string_view'
    bool compile (string_view filename,
                  ^
/root/OpenShadingLanguage/src/include/OSL/oslcomp.h:54:19: error: unknown type
      name 'string_view'
                  string_view stdoslpath = string_view());
                  ^
/root/OpenShadingLanguage/src/include/OSL/oslcomp.h:59:26: error: unknown type
      name 'string_view'
    bool compile_buffer (string_view sourcecode, std::string &osobuffer,
                         ^
/root/OpenShadingLanguage/src/include/OSL/oslcomp.h:61:26: error: unknown type
      name 'string_view'
                         string_view stdoslpath = string_view());
                         ^
/root/OpenShadingLanguage/src/include/OSL/oslcomp.h:65:5: error: unknown type
      name 'string_view'
    string_view output_filename () const;
    ^
/root/OpenShadingLanguage/src/include/OSL/oslcomp.h:54:44: error: use of
      undeclared identifier 'string_view'
                  string_view stdoslpath = string_view());
                                           ^
/root/OpenShadingLanguage/src/include/OSL/oslcomp.h:61:51: error: use of
      undeclared identifier 'string_view'
                         string_view stdoslpath = string_view());
                                                  ^
In file included from /root/OpenShadingLanguage/src/liboslcomp/ast.cpp:36:
In file included from /root/OpenShadingLanguage/src/liboslcomp/oslcomp_pvt.h:37:

/root/OpenShadingLanguage/src/liboslcomp/ast.h:340:5: error: unknown type name
      'string_view'
    string_view shadertypename () const;
    ^
In file included from /root/OpenShadingLanguage/src/liboslcomp/ast.cpp:36:
/root/OpenShadingLanguage/src/liboslcomp/oslcomp_pvt.h:69:19: error: unknown
      type name 'string_view'
    bool compile (string_view filename,
                  ^
/root/OpenShadingLanguage/src/liboslcomp/oslcomp_pvt.h:71:19: error: unknown
      type name 'string_view'
                  string_view stdoslpath);
                  ^
/root/OpenShadingLanguage/src/liboslcomp/oslcomp_pvt.h:73:26: error: unknown
      type name 'string_view'
    bool compile_buffer (string_view sourcecode,
                         ^
/root/OpenShadingLanguage/src/liboslcomp/oslcomp_pvt.h:76:26: error: unknown
      type name 'string_view'
                         string_view stdoslpath);
                         ^
/root/OpenShadingLanguage/src/liboslcomp/oslcomp_pvt.h:249:5: error: unknown
      type name 'string_view'
    string_view output_filename () const { return m_output_filename; }
    ^
/root/OpenShadingLanguage/src/liboslcomp/oslcomp_pvt.h:249:51: error: no viable
      conversion from 'const std::string' (aka 'const basic_string<char>') to
      'int'
    string_view output_filename () const { return m_output_filename; }
                                                  ^~~~~~~~~~~~~~~~~
/root/OpenShadingLanguage/src/liboslcomp/ast.cpp:204:1: error: unknown type name

```
  'string_view'
```

string_view
^
19 errors generated.
src/liboslcomp/CMakeFiles/oslcomp.dir/build.make:70: recipe for target 'src/libo
slcomp/CMakeFiles/oslcomp.dir/ast.cpp.o' failed
make[3]: **\* [src/liboslcomp/CMakeFiles/oslcomp.dir/ast.cpp.o] Error 1
make[3]: Leaving directory '/root/OpenShadingLanguage/build/linux64'
CMakeFiles/Makefile2:943: recipe for target 'src/liboslcomp/CMakeFiles/oslcomp.d
ir/all' failed
make[2]: **\* [src/liboslcomp/CMakeFiles/oslcomp.dir/all] Error 2
make[2]: Leaving directory '/root/OpenShadingLanguage/build/linux64'
Makefile:143: recipe for target 'all' failed
make[1]: **\* [all] Error 2
make[1]: Leaving directory '/root/OpenShadingLanguage/build/linux64'
Makefile:198: recipe for target 'cmake' failed
make: **\* [cmake] Error 2

**Comment by brechtvl** [comment]
You need to build against OpenImage 1.4 or higher, it seems you are using version 1.3. I guess that means building it yourself or getting a newer package from e.g. here:
https://launchpad.net/ubuntu/+source/openimageio

**Comment by unicomp21** [comment]
I get exceptions when adding the ppa.  Building it myself sends me down the rabbit hole with openexr, etc.

**Comment by unicomp21** [comment]
I'd love to get this puppy building on Linux.  I realize it works in Blender as a renderer, but I want to use OSL directly thru it's command line tools, etc.

**Comment by brechtvl** [comment]
Ok, if installing the ubuntu package for OIIO doesn't work, then either you'll have to build OIIO 1.4 or newer manually first, or use an older OSL version.

**Comment by unicomp21** [comment]
I tried building the latest OIIO, and it ends up with broken deps on ilm
components.

**Comment by unicomp21** [comment]
I'd love to be able to use the latest version.

**Comment by abergmeier** [comment]
Is there a OSL developer I can get in contact with to fix building on Ubuntu/Debian? There are multiple problems on 15.10. Should not be too hard to fix this properly.

**Comment by lgritz** [comment]
I think this would be a good question to ask on the osl-dev mail list, which has a much wider audience than those who monitor the GitHub "issues".

I, unfortunately, don't have easy access to an Ubuntu/Debian machine, so this isn't something I can reliably work out myself, except in cases where I just happen to be able to diagnose the likely problem by looking at the build logs.

**Comment by lgritz** [comment]
Closing, this references a very old version. Make a new issue if it's still a problem with modern OSL.
